// Add your code here

// let words_RA6_08: string[][] = [
//     ["possible", "形 可能，可能发生的"],
//     ["can't help but do...", "不能停止做某事，忍不住做某事"],
//     ["nervous", "形 紧张不安的"],
//     ["nod", "动 点头同意，点头许可"],
//     ["discuss", "动 讨论，谈论"],
//     ["consider", "动 认为，视为"],
//     ["further", "形 更多的，进一步的"],
//     ["notice", "名 通知，通告"],
//     ["further notice", "进一步的通知"],
//     ["until further notice", "直至另行通知"],
//     ["muffle", "动 减低，降低(声音)"],
//     ["conversation", "名 (非正式的)交谈，谈话"],
//     ["toss", "动 抛，扔"],
//     ["over", "副 又，再一次"],
//     ["hold out", "伸出，递出"],
//     ["meatloaf", "名 肉饼"],
//     ["mash", "动 捣烂，把(食物等)捣成糊状"],
//     ["mashed potatoes", "豆泥"],
//     ["broccoli", "名 西兰花"],
//     ["roll one's eyes", "（某人)翻白眼"],
//     ["figure", "动 预料，认为"],
//     ["find out", "发现，弄清"],
//     ["anyway", "副 不管怎样"],
//     ["freak", "动 使心烦意乱"],
//     ["freak out", "心里乱极了，吓坏了"],
//     ["reply", "动 回答，答复"],
//     ["sheepish", "形 (尤指做了傻事或错事后)羞怯的，窘迫的"],
//     ["sniff", "动 嗅，闻"],
//     ["ask", "动 请求，征求"],
//     ["repay", "动 报答"],
//     ["exactly", "副 确切地，准确地"],
//     ["on", "介 是…一员，在列表中"],
//     ["actually", "副 实际上，事实上"],
//     ["relieved", "形 放心的，宽慰的"],
//     ["repeat", "动 重复一遍"],
//     ["shot", "名 投篮"],
//     ["perfect", "形 完美的，极其准确的"],
//     ["be perfect at", "极其擅长于"],
//     ["purpose", "名 目的，意图"],
//     ["on purpose", "故意地"],
//     ["all that...", "如此，那么"],
//     ["forth", "副 向前"],
//     ["back and forth", "前前后后地"],
//     ["sense", "名 意义，理由"],
//     ["make sense", "有意义，是明智的"],
//     ["shrug", "动 耸肩"],
//     ["stupid", "形 不明智的，愚蠢的"],
//     ["trick", "动 蒙骗"],
//     ["trick sb. into doing...", "诱使某人做某事"],
// ]
